# Generated by Django 4.2.7 on 2023-11-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_productbuy_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbuy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productbuy',
            name='modeofpayment',
        ),
        migrations.RemoveField(
            model_name='productbuy',
            name='product',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProductBuy',
        ),
    ]
