# Generated by Django 4.2.5 on 2023-11-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
